config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/stages/large', to: 'stages#stages_large'
  get '/stages/small', to: 'stages#stages_small'
  resources :stages
  resources :artists do
    resources :performances, only: [:index, :new, :create]
  end
  resources :performances, only: [:index, :new, :create]

  root to: 'sessions#welcome'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    belongs_to :user
    has_many :performances
    has_many :stages, through: :performances

    validates :name, presence: true
    validates :genre, presence: true
    validates :name, uniqueness: true

    def duration
        self.performances.sum do |performance|
            performance.duration
        end
    end
end

app/models/performance.rb
class Performance < ApplicationRecord
    belongs_to :stage
    belongs_to :artist
    validates_presence_of :duration
end

app/models/stage.rb
class Stage < ApplicationRecord
    has_many :performances
    has_many :artists, through: :performances
    scope :large, -> { where('capacity > 500') }
    scope :small, -> { where('capacity < 500') }

    #would it be easier to build a scope method that just orders stages in order of highest to lowest capacity?

    validates :name, presence: true
    validates :name, uniqueness: true


end

app/models/user.rb
class User < ApplicationRecord
    has_many :artists
    validates_presence_of :username, :password
    validates_uniqueness_of :username
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        User.find_by(id: session[:user_id])
    end

    def require_login
        redirect_to login_path unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def log_in(user)
        session[:user_id] = user.id
    end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :require_login, only: [:new, :create]

    def index
        @artists = current_user.artists
    end

    def new
        @artist = Artist.new #setting a variable to be accessible to the form_for view
    end

    def create
        @artist = current_user.artists.build(artist_params)
        if @artist.save
            redirect_to new_artist_performance_path(@artist)
        else
            render :new
        end
    end

    def update
        if @artist.update(artist_params)
            render :show
        else
            render :edit
        end
    end

    private

    def artist_params
        params.require(:artist).permit(:name, :genre)
    end

end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
    before_action :require_login
    before_action :get_artist, only: [:index, :new, :create]

    def index
        redirect_invalid_request
    end

    def new
        redirect_invalid_request
        @performance = Performance.new
    end

    def create
        @artist = Artist.find_by(id: params[:performance][:artist_id])
        if user_authorized?
            # binding.pry
            @performance = Performance.new(performance_params)
            if @performance.save
                redirect_to artist_performances_path(@performance.artist)
            else
                render :new
            end
        else
            redirect_to artists_path
        end
    end
    
    private

    def get_artist
        @artist ||= Artist.find_by(id: params[:artist_id])
    end

    def user_authorized?
         @artist.user && (@artist.user_id == current_user.id)
    end

    def redirect_invalid_request
        if @artist.nil? || !user_authorized?
            redirect_to sequences_path
        end
    end

    def performance_params
        params.require(:performance).permit(:stage_id, :stage, :duration, :description, :artist_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    #    binding.pry
    end

    def create
        # raise_params
        if request.env["omniauth.auth"]
            @user = User.find_by(github_uid: request.env["omniauth.auth"]["uid"])
            if @user.nil?
                @user = User.create(username: request.env["omniauth.auth"]["info"]["nickname"], github_uid: request.env["omniauth.auth"]["uid"], password: SecureRandom.hex)
                # log_in(@user)
                # redirect_to stages_path
            end
                log_in(@user)
                redirect_to stages_path
        else
            @user = User.find_by(username: params[:username])
            if !@user
                @error = "Account not found. Please try again."
                render :new
            elsif !@user.authenticate(params[:password])
                @error = "Password incorrect. Please try again."
                wrender :new
            else
                log_in(@user)
                redirect_to stages_path
            end
        end
    end

    def destroy
        session.clear
        redirect_to root_path
    end


end

app/controllers/stages_controller.rb
class StagesController < ApplicationController
    before_action :require_login, only: [:new, :create]
    before_action :set_stage, only: [:edit, :update, :destroy]

    def index
        @stages = Stage.all
    end

    def new
        @stage = Stage.new
    end

    def create
        @stage = Stage.new(stage_params)
        if @stage.save
            redirect_to stages_path(@stage)
        else
            render :new
        end
    end

    def show
        stage_params
    end

    def stages_large
        @stages = Stage.large
        render :index
    end

    def stages_small
        @stages = Stage.small
        render :index
    end

    private

    def set_stage
        @stage = Stage.find(params[:id])
    end

    def stage_params
        params.require(:stage).permit(:name, :capacity)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        log_in(@user)
        redirect_to stages_path
      else
        render :new
      end
    end

    private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper

end

app/helpers/performances_helper.rb
module PerformancesHelper
    def duration_to_minutes(duration)
        "#{duration / 60} minutes and #{duration % 60} seconds"
     end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !!current_user
    end

end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/application/welcome.html.erb
<!DOCTYPE html>

<html>
<head>
<title>EZManager</title>
</head>

<body>
<h1>Welcome to EZ-Manager</h1>

</body>

</html>

app/views/artists/index.html.erb
<h1><%= current_user.username %>'s Artists:</h1>

<%= link_to "Create New Artist", new_artist_path %>

<ul>
    <% @artists.each do |artist| %>
        <li>
            Name: <%= link_to artist.name, artist_performances_path(artist) %>
        </li>
        <li>
            Genre: <%= artist.genre %>
        </li>
        <li>
            Performances: <%= artist.performances.count %>
        <br><br>
    <%end%>
</ul>

app/views/artists/new.html.erb
<h2> Create a new Artist! </h2>

<%= render partial: '/errors', locals: { record: @artist } %>

<%= form_for(@artist) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :genre %>
    <%= f.text_field :genre %>
    <%= f.submit %>
    <% end %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @artist.email %>
</p>

<p>
  <strong>Performances:</strong>
  <%= @artist.performances %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/_navbar.html.erb
<div class="header">
    <div class="title">EZ Manager</div>
    <% if current_user %>
        <div class="username">
            <p>Welcome, <%= current_user.username %></p>
        </div>
    <% end %>
    <div class="nav">
        <% if logged_in? %>
            <div><a href="/stages">My Stages</a></div>
            <div><a href="/artists">My Artists</a></div>
            <div><a href="/logout">Log Out</a></div>
        <% else %>
            <div><a href="/signup">Sign Up</a></div>
            <div><a href="/login">Log In</a></div>
        <% end %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EZManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <navbar>
    <%= render 'layouts/navbar' %>
    </navbar>
    <main class="wrapper">
    </main>
    <%= yield %>
  </body>
</html>

app/views/performances/index.html.erb
<h2> All the performances of <i><%= @artist.name %>:</i></h2>

<%= link_to "Add New Performance", new_artist_performance_path(@artist) %>

<% @artist.performances.each.with_index(1) do |performance, index|%>
       <h3><%= index %>. <%= performance.stage.name %></h3>
       <p>Duration: <%= performance.duration%></p>
       <p>Set Description: <%= performance.description%></p>
<% end %>

app/views/performances/new.html.erb
<h2> Add a new Performance for <i><%= @artist.name %></i></h2>

<%= render partial: '/errors', locals: { record: @performance } %>


<%= form_for @performance do |f| %>
    <%= f.label :Stage %>
    <div><%= f.collection_select :stage_id, Stage.all, :id, :name, prompt: true %></div>
    <%= f.label :Duration %>(min)
    <div><%= f.number_field :duration %></div>
    <%= f.label :Description %>
    <div><%= f.text_area :description %></div>
    <%= f.hidden_field :artist_id, value: @artist.id %>
    <%= f.submit %>
<% end %>

app/views/stages/edit.html.erb
<h1>Edit Stage</h1>

<%= render 'form', stage: @stage %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<h1>Get Started with creating a new stage!</h1>
<%= link_to "Create New Stage", new_stage_path%>
<br>
<%= link_to "Create New Artist", new_artist_path%>
<br>
<h2> Stages: </h2>
<%= link_to "Large Stages", stages_large_path%>
<br>
<%= link_to "Small Stages", stages_small_path%>
<br>
<ul>
    <% @stages.each do |stage| %>
        <li>
        Stage: <%= stage.name %>
        </li>
        <li>
        Capacity: <%= stage.capacity%>
        </li>
        <br>
    <%end%>
</ul>

app/views/stages/new.html.erb
<h1> New Stage </h1>

<%= render partial: '/errors', locals: { record: @stage } %>

<%= form_for(@stage) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :capacity %>
    <%= f.text_field :capacity %>
    <%= f.submit %>
    <% end %>

app/views/stages/show.html.erb
<h1><%= @stage.name %></h1>
<br>
<h4><%= @stage.performances %></h4>
<br>
<h4><%= @stage.capacity %></h4>

<%= link_to "Edit Stage", edit_stage_path %>

app/views/users/new.html.erb
<h2>  Create a user account </h2>

<%= render partial: '/errors', locals: { record: @user } %>

<%= form_for @user, url: signup_path do |f| %>
  <%= f.label :Username %>
  <div><%= f.text_field :username %></div>
  <%= f.label :Password %>
  <div><%= f.password_field :password %></div>
  <%= f.label :confirm_password %>
  <div><%= f.password_field :password_confirmation %>
  <%= f.submit %>
<% end %>